### ISSUE TITLE
Requires SQL::Translator

### ISSUE THREAD

**Issue by wcravens** [tempire/MojoExample#2]
```
$ prove -l
```

t/blogs.t ... DBIx::Class::Schema::deploy(): Can't deploy without a ddl_dir or SQL::Translator >= 0.11006 (see DBIx::Class::Optional::Dependencies for details) at /home/wcravens/Repos/MojoExample/lib/Test/Database.pm line 38

This is not mentioned in the dependencies.

Installing SQL::Translator fixed the problem.

**Comment by tempire** [comment]
Included.
