### ISSUE TITLE
Replace URLs in redirect_to into name of routes

### ISSUE THREAD

**Issue by sharifulin** [tempire/MojoExample#6]
You use absolute URL in redirect_to methods, it's no good.
Better solution is using name of routes, i.e.:

``` perl
$r->route('/foo/bar')->to('foo#bar')->name('foo_bar');

$self->redirect_to('foo_bar');
```

**Comment by tempire** [comment]
Indeed.  That should be changed.

**Comment by tempire** [comment]
Updated redirects to use implicit route names.  Thanks @sharifulin :)
