### ISSUE TITLE
how to use mojolicious on windows 

### ISSUE THREAD

**Issue by avay** [tempire/MojoExample#7]
Hi,
I am a new learner and i really interested in using his web framework on windows.
I have installed Strawberry Perl on windows 32 bit. I also installed Mojolicious  using Cpan .
but found errors on hitting enter after "morbo hello" like

Can't opendir(templates): Invalid argument
 at C:/Strawberry/perl/site/bin/../lib/Mojo/Home.pm line 66.

I don't know what are the requirements and steps to be followed to simply print a hello on the web.
I need a tutorial or say documentation for windows.
Thanks in advance for helping me

**Comment by chorny** [comment]
See http://mojolicio.us/perldoc/Mojolicious/Guides/Cookbook#Built-in_web_server

**Comment by zoffixznet** [comment]
I know this is ancient, but it just showed up for me on Google:

> Can't opendir(templates): Invalid argument at C:/Strawberry/perl/site/bin/../lib/Mojo/Home.pm line 66.

This is because you're running it in your Windows home dir. It has this "special" `templates` dir in it that users can't read, and `morbo` tries to find the templates dir in the current dir. Just `cd` to another dir.
